language: node.js
node_js:
  - 13

services:
 - docker

install:
  - echo "Nothing for now"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend alsajjad/udagram-frontend:v6

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alsajjad/udagram-frontend:v6