language: node.js
node_js:
  -13

services:
 - docker

install:
  - echo "Nothing for now"

before_script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed alsajjad/udagram-api-feed
  - docker tag udagram-api-user alsajjad/udagram-api-user
  - docker tag udagram-frontend alsajjad/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alsajjad/udagram-api-feed
  - docker push alsajjad/udagram-api-user
  - docker push alsajjad/udagram-frontend