language: node.js
node_js:
  - 13

services:
 - docker

install:
  - echo "Nothing for now"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed alsajjad/udagram-api-feed:v1
  - docker tag udagram-api-user alsajjad/udagram-api-user:v1
  - docker tag udagram-frontend alsajjad/udagram-frontend:v1
  - docker tag udagram-reverseproxy alsajjad/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alsajjad/udagram-api-feed:v1
  - docker push alsajjad/udagram-api-user:v1
  - docker push alsajjad/udagram-frontend:v1
  - docker push alsajjad/udagram-reverseproxy:v1