apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: alsajjad/udagram-reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
      restartPolicy: Always